# Generated by Django 4.2 on 2023-06-21 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteCarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('images', models.ImageField(upload_to='siteFiles/%Y/%m/%d/')),
            ],
        ),
    ]
