# Generated by Django 4.2 on 2023-06-21 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitecarousel',
            old_name='images',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='sitecarousel',
            name='title',
            field=models.TextField(max_length=500),
        ),
    ]
