# Generated by Django 4.2 on 2023-06-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rename_images_sitecarousel_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecarousel',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
