# Generated by Django 4.2 on 2023-06-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_sitecarousel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecarousel',
            name='image',
            field=models.ImageField(upload_to='carousels/'),
        ),
    ]
