# Generated by Django 4.2 on 2023-06-27 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_shoppingcart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingcart',
            old_name='items',
            new_name='product',
        ),
    ]
