# Generated by Django 4.2 on 2023-06-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='products',
            field=models.ManyToManyField(to='products.shoppingcart'),
        ),
    ]
