# Generated by Django 4.2 on 2023-06-28 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_payment_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='total',
            field=models.IntegerField(),
        ),
    ]
