# Generated by Django 4.2 on 2023-06-28 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_alter_payment_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='isCompleted',
            field=models.BooleanField(default=False),
        ),
    ]
